using System;
using System.Linq;
using UnityEngine;
using UnityEditor;
using static StudentWork.CandyWonderland.Editor.CandyMeshKit;
namespace StudentWork.CandyWonderland.Editor {
 public static class CandyVariants {
  public static readonly string[] Names={"Classic Swirl","Heart Swirl","Starlight Candy","Twisted Rope","Mint Striped Globe","Flower Glass","Citrus Slice","Chocolate Sprinkle","Soft Serve Tree"};
  public static GameObject[] Create(){var result=new GameObject[9];for(int i=0;i<9;i++){string path=Art+"/"+Names[i]+".prefab";result[i]=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(result[i])UpgradeCrystal(path,i);if(result[i]&&result[i].transform.Find("Candy crown").GetComponent<BoxCollider>()&&result[i].GetComponentsInChildren<MeshRenderer>().Any(r=>r.name=="Batched candy decoration"))continue;if(result[i]){var content=PrefabUtility.LoadPrefabContents(path);CrownCollider(content.transform,i);if(!content.GetComponentsInChildren<MeshRenderer>().Any(r=>r.name=="Batched candy decoration")){CombineVisuals(content.transform,Names[i]);PrefabUtility.SaveAsPrefabAsset(content,path);}PrefabUtility.SaveAsPrefabAsset(content,path);PrefabUtility.UnloadPrefabContents(content);continue;}var root=new GameObject(Names[i]);Build(root.transform,i);CrownCollider(root.transform,i);CombineVisuals(root.transform,Names[i]);result[i]=PrefabUtility.SaveAsPrefabAsset(root,path);UnityEngine.Object.DestroyImmediate(root);}return result;}
  static void UpgradeCrystal(string path,int kind){string original=kind==1?"Rose glaze":kind==2?"Sugar gold":kind==6?"Apricot candy":null;if(original==null)return;var asset=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(!asset.GetComponentsInChildren<MeshRenderer>().Any(r=>r.sharedMaterial&&r.sharedMaterial.name==original))return;var content=PrefabUtility.LoadPrefabContents(path);var color=kind==1?new Color(1,.47f,.67f,.84f):kind==2?new Color(1,.82f,.5f,.86f):new Color(1,.68f,.43f,.78f);var material=Mat(Names[kind]+" translucent glaze",color,.94f,true);foreach(var renderer in content.GetComponentsInChildren<MeshRenderer>())if(renderer.sharedMaterial&&renderer.sharedMaterial.name==original)renderer.sharedMaterial=material;PrefabUtility.SaveAsPrefabAsset(content,path);PrefabUtility.UnloadPrefabContents(content);}
  static void CrownCollider(Transform root,int kind){var crown=root.Find("Candy crown");if(!crown||crown.GetComponent<BoxCollider>())return;var box=crown.gameObject.AddComponent<BoxCollider>();box.center=kind==3||kind==8?new Vector3(0,1.7f,0):Vector3.zero;box.size=kind==3?new Vector3(1.9f,3.9f,1.9f):kind==8?new Vector3(3.2f,4,3.2f):kind==4?Vector3.one*2.7f:new Vector3(3.1f,3.1f,.56f);}
  static Vector2 Heart(float t){return new Vector2(16*Mathf.Pow(Mathf.Sin(t),3),13*Mathf.Cos(t)-5*Mathf.Cos(2*t)-2*Mathf.Cos(3*t)-Mathf.Cos(4*t))/17;}
  static Vector2 Star(float t){float period=Mathf.Repeat(t/(2*Mathf.PI)*10,2);float r=Mathf.Lerp(1,.46f,period<1?period:2-period);return new Vector2(Mathf.Sin(t),Mathf.Cos(t))*r;}
  static void Build(Transform root,int kind){
   var pink=Mat("Rose glaze",new Color(1,.36f,.61f));var cream=Mat("Vanilla icing",new Color(1,.94f,.84f));var mint=Mat("Pistachio candy",new Color(.6f,.86f,.7f));var peach=Mat("Apricot candy",new Color(1,.68f,.48f));var gold=Mat("Sugar gold",new Color(1,.79f,.37f));var lavender=Mat("Lilac sugar",new Color(.77f,.64f,.94f));var chocolate=Mat("Milk chocolate",new Color(.3f,.13f,.11f));var glass=Mat("Rose candy glass",new Color(1,.62f,.76f,.42f),.98f,true);
   var stem=Primitive("Vanilla stick",root,PrimitiveType.Cylinder,new Vector3(0,2.6f,0),new Vector3(.19f,2.6f,.19f),cream);var solid=stem.AddComponent<BoxCollider>();solid.size=new Vector3(1,2,1);
   var head=new GameObject("Candy crown").transform;head.SetParent(root,false);head.localPosition=new Vector3(0,5.2f,0);
   if(kind==3||kind==8){
    head.localPosition=Vector3.up*3.3f;
    for(int strand=0;strand<2;strand++){int k=strand;var points=Curve(t=>{float r=kind==8?1.2f*(1-t)+.09f:.55f;float a=t*Mathf.PI*(kind==8?9:7)+k*Mathf.PI;return new Vector3(Mathf.Cos(a)*r,t*3.4f,Mathf.Sin(a)*r);});Part("Hand twisted "+(k==0?"mint":"cream"),head,Save(Names[kind]+" strand "+k,Tube(points,kind==8?.36f:.3f,12)),k==0?mint:cream,Vector3.zero);}
   }else if(kind==4){var globe=Primitive("Striped mint globe",head,PrimitiveType.Sphere,Vector3.zero,Vector3.one*2.7f,StripeMaterial("Mint globe glaze",mint.GetColor("_BaseColor")));globe.GetComponent<MeshRenderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.On;
   }else{
    Func<float,Vector2> shape=kind==1?Heart:kind==2?Star:(Func<float,Vector2>)(t=>new Vector2(Mathf.Cos(t),Mathf.Sin(t)));
    var disk=Part("Beveled candy face",head,Save(Names[kind]+" crown",Shape(shape,.13f)),kind==5?glass:kind==6?peach:kind==2?gold:pink,Vector3.zero);disk.transform.localScale=Vector3.one*1.45f;
    var rim=Part("Rounded cream rim",head,Save(Names[kind]+" rim",Tube(Curve(t=>{var p=shape(t*Mathf.PI*2);return new Vector3(p.x,p.y,0);},129),.065f,10)),kind==2?pink:cream,Vector3.zero);rim.transform.localScale=Vector3.one*1.45f;
    if(kind==0||kind==1){for(int face=0;face<2;face++){int sign=face==0?1:-1;var spiral=Curve(t=>{float a=t*Mathf.PI*6;var p=new Vector2(Mathf.Cos(a),Mathf.Sin(a))*(.03f+t*.92f);if(kind==1){var boundary=Heart(Mathf.Atan2(p.x,p.y));p=new Vector2(p.x,p.y)*.74f;p.y+=.13f;}return new Vector3(p.x,p.y,sign*.155f);});var g=Part("Cream spiral "+face,head,Save(Names[kind]+" spiral "+face,Tube(spiral,.095f,10)),cream,Vector3.zero);g.transform.localScale=Vector3.one*1.45f;}}
    if(kind==2){var inner=Part("Pink inner star",head,Save("Small embossed star",Shape(Star,.04f)),pink,new Vector3(0,0,-.24f));inner.transform.localScale=Vector3.one*.9f;var inner2=Part("Cream star highlight",head,inner.GetComponent<MeshFilter>().sharedMesh,cream,new Vector3(0,0,-.3f));inner2.transform.localScale=Vector3.one*.43f;}
    if(kind==5){for(int n=0;n<7;n++){float a=n*2.399f;var center=new Vector3(Mathf.Cos(a)*(.3f+n*.095f),Mathf.Sin(a)*(.3f+n*.095f),-.21f);var petal=n%2==0?pink:gold;for(int k=0;k<5;k++){float b=k*Mathf.PI*2/5;Primitive("Sugar flower petal",head,PrimitiveType.Sphere,center+new Vector3(Mathf.Cos(b),Mathf.Sin(b),0)*.16f,new Vector3(.22f,.17f,.06f),petal);}Primitive("Flower heart",head,PrimitiveType.Sphere,center,new Vector3(.11f,.11f,.065f),mint);}}
    if(kind==6){for(int k=0;k<8;k++){float a=k*Mathf.PI/4;var points=new[]{new Vector3(0,0,-.22f),new Vector3(Mathf.Cos(a)*1.35f,Mathf.Sin(a)*1.35f,-.22f)};Part("Citrus segment membrane",head,Save("Citrus radial "+k,Tube(points,.035f)),cream,Vector3.zero);}var p=Primitive("Citrus center",head,PrimitiveType.Sphere,new Vector3(0,0,-.22f),Vector3.one*.18f,cream);}
    if(kind==7){var cap=Primitive("Chocolate dipped crown",head,PrimitiveType.Sphere,new Vector3(0,.57f,0),new Vector3(2.55f,1.55f,.46f),chocolate);for(int k=0;k<8;k++)Primitive("Chocolate drip",head,PrimitiveType.Sphere,new Vector3(-1.07f+k*.305f,.06f+.14f*Mathf.Sin(k*3),-.21f),new Vector3(.23f,.48f+.18f*Mathf.Sin(k),.17f),chocolate);var random=new System.Random(47);for(int k=0;k<28;k++){var sprinkle=Primitive("Rainbow sugar sprinkle",head,PrimitiveType.Capsule,new Vector3((float)random.NextDouble()*2.1f-1.05f,.35f+(float)random.NextDouble()*.74f,-.31f),new Vector3(.05f,.075f,.05f),new[]{pink,mint,gold,lavender}[k%4]);sprinkle.transform.localRotation=Quaternion.Euler(0,0,(float)random.NextDouble()*180);}}
   }
   if(kind%3==0){for(int side=-1;side<=1;side+=2){var bow=Primitive("Satin bow loop",root,PrimitiveType.Sphere,new Vector3(side*.28f,3.95f,-.16f),new Vector3(.55f,.3f,.16f),pink);bow.transform.localRotation=Quaternion.Euler(0,0,side*-25);}Primitive("Bow knot",root,PrimitiveType.Sphere,new Vector3(0,3.95f,-.2f),Vector3.one*.2f,gold);}
  }
  public static Material StripeMaterial(string name,Color color){string path=Art+"/"+name+".mat";var existing=AssetDatabase.LoadAssetAtPath<Material>(path);if(existing)return existing;var m=new Material(Shader.Find("StudentWork/Rolling Striped Candy")){name=name};m.SetColor("_BaseColor",color);m.SetColor("_CreamColor",new Color(1,.96f,.86f));AssetDatabase.CreateAsset(m,path);return m;}
 }
}
