using System;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using DigiPhant;
using static StudentWork.CandyWonderland.Editor.CandyMeshKit;
namespace StudentWork.CandyWonderland.Editor {
 public static class CandyWonderlandSetup {
  public const string ScenePath="Assets/StudentWork/Scenes/Level1_CandyWonderland.unity";
  static Material pink,cream,mint,gold,cake,wood,lilac,cloud,peach;
  static List<BoxCollider> solids;
  static System.Random rng;
  [MenuItem("DigiPhant/Candy Wonderland/Generate reusable candy models")]
  public static void Generate(){CandyVariants.Create();AssetDatabase.SaveAssets();Debug.Log("CANDY_VARIANTS_READY: nine distinct reusable procedural candy prefabs");}
  [MenuItem("DigiPhant/Candy Wonderland/Build new scene variant")]
  public static void Build(){BuildVariant(true);}
  public static void BuildVariant(bool elevated){
   if(EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Stop Play mode before building");
   var source=SceneManager.GetActiveScene();int selectedSeed=source.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<CandyWorld>(true)).Select(w=>w.placementSeed).DefaultIfEmpty(4817).First();if(source.path==ScenePath){EditorSceneManager.SaveScene(source);AssetDatabase.CopyAsset(ScenePath,AssetDatabase.GenerateUniqueAssetPath("Assets/StudentWork/Scenes/Level1_CandyWonderland_DraftBackup.unity"));source=EditorSceneManager.OpenScene("Assets/DigiPhant/Scenes/DigiPhant.unity",OpenSceneMode.Single);}
   if(!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())return;
   string sourcePath=source.path;
   if(!EditorSceneManager.SaveScene(source,ScenePath,true))throw new Exception("Could not create independent scene copy");
   var scene=EditorSceneManager.OpenScene(ScenePath,OpenSceneMode.Single);var all=scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<Transform>(true)).ToArray();
   var loco=all.Select(t=>t.GetComponent<DigiPhantLocomotion>()).Single(x=>x);var movement=loco.GetComponent<StudentObstacleMovement>();var finish=all.Select(t=>t.GetComponent<RibbonFinish>()).Single(x=>x);var pickup=loco.GetComponent<LollipopPickup>();var forest=all.Select(t=>t.GetComponent<LollipopForest>()).Single(x=>x);
   // Preserve original scenery and all authored gameplay objects in the copied scene.
   foreach(var t in all.Where(t=>t.name=="Ground"||t.name=="Stage"||t.name=="Stage distance grid (4 units)"||t.name=="Open path"||t.name.StartsWith("Acacia ")||t.name=="04 Finish marker"))t.gameObject.SetActive(false);
   foreach(var t in forest.giantLollipops)t.gameObject.SetActive(false);
   foreach(var p in all.Select(t=>t.GetComponent<CourseObstacleProxy>()).Where(p=>p))p.gameObject.SetActive(true);
   foreach(var oldBall in forest.rollingBalls)oldBall.gameObject.SetActive(false);
   // Hide old course signposts / grid guides; edible candy, pond and banana remain.
   foreach(var t in all.Where(t=>t.name.StartsWith("X ")||t.name=="Boundary posts"||t.name=="Course labels"||t.name=="Wayfinding"||t.name=="Chevrons"))t.gameObject.SetActive(false);
   rng=new System.Random(selectedSeed);solids=new List<BoxCollider>();Materials();
   var root=new GameObject("Level 1 - Candy Wonderland");var world=root.AddComponent<CandyWorld>();world.elevated=elevated;world.placementSeed=selectedSeed;
   var environment=Group("Environment",root.transform);var vegetation=Group("Candy vegetation",root.transform);var atmosphere=Group("Atmosphere",root.transform);var obstacles=Group("Rolling candy challenge",root.transform);
   var knots=new[]{new Vector3(0,0,0),new Vector3(0,0,6),new Vector3(-12,0,7),new Vector3(-19,0,1),new Vector3(-19,0,-11),new Vector3(-12,0,-17),new Vector3(12,0,-17),new Vector3(19,0,-10),new Vector3(19,0,12),new Vector3(13,0,18),new Vector3(-16,0,18)};
   var route=new List<Vector3>();for(int segment=0;segment<knots.Length-1;segment++)for(int step=0;step<24;step++){float t=step/24f;var a=knots[Mathf.Max(0,segment-1)];var b=knots[segment];var c=knots[segment+1];var d=knots[Mathf.Min(knots.Length-1,segment+2)];var p=.5f*((2*b)+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t);float progress=(segment+t)/(knots.Length-1);p.y=elevated?Elevation(progress):0;route.Add(p);}var last=knots.Last();last.y=elevated?Elevation(1):0;route.Add(last);float totalLength=0;for(int i=1;i<route.Count;i++)totalLength+=Vector2.Distance(new Vector2(route[i].x,route[i].z),new Vector2(route[i-1].x,route[i-1].z));float travelled=0;for(int i=0;i<route.Count;i++){if(i>0)travelled+=Vector2.Distance(new Vector2(route[i].x,route[i].z),new Vector2(route[i-1].x,route[i-1].z));var point=route[i];point.y=elevated?Elevation(travelled/totalLength):0;route[i]=point;}world.route=route.ToArray();world.pathHalfWidth=4.8f;
   BuildPath(environment,world);BuildIslands(environment,world);BuildVegetation(vegetation,world,movement);BuildBridges(environment,world);BuildWaterfalls(environment,world);world.castle=BuildCastle(environment,world.route.Last());
   // Reposition the existing finish as a single unit; its logic, refs and ribbon stay intact.
   finish.transform.position=world.route.Last()+new Vector3(0,.02f,0);finish.transform.rotation=Quaternion.Euler(0,-90,0);
   var edibleTree=all.FirstOrDefault(t=>t.name=="Pink Swirl Lollipop Tree");if(edibleTree){var pos=new Vector3(-7,world.GroundHeight(new Vector3(-7,0,18)),23.2f);edibleTree.position=pos;}
   // Keep the original pond, peel, bush and timber visible on the new landscape.
   var pond=all.Single(t=>t.name=="02 Water basin");pond.position=new Vector3(6,.03f,2.5f);
   var bush=all.Single(t=>t.name=="01 Feeding bush");bush.position=new Vector3(-6,.03f,2.7f);
   var timber=all.Single(t=>t.name=="03 Fallen log");timber.position=new Vector3(24f,world.GroundHeight(new Vector3(19,0,-6))+.03f,-6);
   var timberLedge=Part("Preserved timber cake ledge",environment,AssetDatabase.LoadAssetAtPath<Mesh>(Art+"/Organic floating cake island.asset"),cake,timber.position);timberLedge.transform.localScale=new Vector3(3,.3f,2.7f);
   var banana=all.FirstOrDefault(t=>t.name=="Banana Peel beside Pond");if(banana)banana.position=pond.position+new Vector3(2.242841f,.03485f,.6f);
   foreach(var proxy in all.Select(t=>t.GetComponent<CourseObstacleProxy>()).Where(p=>p))proxy.SyncBounds();
   solids.AddRange(world.castle.GetComponentsInChildren<BoxCollider>());BuildBalls(obstacles,world,movement,loco,finish);BuildAtmosphere(atmosphere,world);var clearance=root.AddComponent<CandyCameraClearance>();clearance.gameplayCamera=loco.followCamera;clearance.elephant=loco.travelRoot;clearance.decorations=vegetation.GetComponentsInChildren<Renderer>().Concat(atmosphere.GetComponentsInChildren<MeshRenderer>()).Where(r=>r.enabled).ToArray();StyleTitle(forest.introduction);ConfigureLighting(environment,loco.followCamera);
   // Retain old refs; only active new obstruction geometry participates in the SAT solver.
   movement.obstacles=movement.obstacles.Concat(solids).ToArray();EditorUtility.SetDirty(movement);
   if(elevated)InstallGrounding(loco,world);
   CombineVisuals(environment,"Static candy kingdom");Physics.SyncTransforms();AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);
   Debug.Log("CANDY_WONDERLAND_BUILT: "+ScenePath+"; source preserved: "+sourcePath+"; elevated="+elevated+"; "+world.route.Length+" route samples, nine candy prefabs, castle, bridges, waterfalls, balloons and clouds");
  }
  static void InstallGrounding(DigiPhantLocomotion loco,CandyWorld world){var adapter=loco.gameObject.AddComponent<CandyTerrainGrounding>();adapter.locomotion=loco;adapter.world=world;}
  public static float Elevation(float t){return 5.8f*Mathf.SmoothStep(0,1,t)+Mathf.Sin(t*Mathf.PI*6)*.65f*Mathf.Sin(t*Mathf.PI);}
  static Transform Group(string name,Transform parent){var g=new GameObject(name);g.transform.SetParent(parent,false);return g.transform;}
  static Material ShaderMaterial(string name,string shader){var path=Art+"/"+name+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(!mat){mat=new Material(Shader.Find(shader)){name=name};AssetDatabase.CreateAsset(mat,path);}return mat;}
  static void Materials(){pink=Mat("Rose glaze",new Color(1,.36f,.61f));cream=Mat("Vanilla icing",new Color(1,.94f,.84f));mint=Mat("Pistachio candy",new Color(.6f,.86f,.7f));gold=Mat("Sugar gold",new Color(1,.79f,.37f));lilac=Mat("Lilac sugar",new Color(.77f,.64f,.94f));cake=Mat("Strawberry cake",new Color(.78f,.47f,.41f),.22f);wood=Mat("Biscuit fence",new Color(.55f,.29f,.18f),.28f);cloud=ShaderMaterial("Marshmallow cloud","StudentWork/CandyWonderland/Sugar Cloud");cloud.shader=Shader.Find("StudentWork/CandyWonderland/Sugar Cloud");cloud.SetColor("_BaseColor",new Color(.99f,.94f,.96f));peach=Mat("Peach frosting",new Color(1,.74f,.69f));}
  static Material LavenderCloud(){var mat=ShaderMaterial("Lavender cloud","StudentWork/CandyWonderland/Sugar Cloud");mat.shader=Shader.Find("StudentWork/CandyWonderland/Sugar Cloud");mat.SetColor("_BaseColor",new Color(.88f,.84f,.97f));return mat;}
  static float Random(float min,float max){return min+(float)rng.NextDouble()*(max-min);}
  static void BuildPath(Transform env,CandyWorld world){
   var parent=Group("Continuous pink candy trail",env);var v=new List<Vector3>();var uv=new List<Vector2>();var tri=new List<int>();var left=new List<Vector3>();var right=new List<Vector3>();float distance=0;
   for(int i=0;i<world.route.Length;i++){var p=world.route[i];var dir=(world.route[Mathf.Min(i+1,world.route.Length-1)]-world.route[Mathf.Max(0,i-1)]);dir.y=0;var side=Vector3.Cross(Vector3.up,dir.normalized);if(i>0)distance+=Vector3.Distance(p,world.route[i-1]);for(int j=0;j<7;j++){float x=(j/6f-.5f)*world.pathHalfWidth*2;v.Add(p+side*x+Vector3.up*(.025f+Mathf.Cos(x/world.pathHalfWidth*Mathf.PI*.5f)*.045f));uv.Add(new Vector2(j/6f,distance*.12f));if(i>0&&j<6){int n=i*7+j,a=n-7;tri.AddRange(new[]{a,n,a+1,a+1,n,n+1});}}left.Add(p-side*world.pathHalfWidth+Vector3.up*.07f);right.Add(p+side*world.pathHalfWidth+Vector3.up*.07f);}
   var road=Part("Walkable frosting surface",parent,Save("Continuous candy trail",CandyMeshKit.Build(v,tri,uv)),peach,Vector3.zero);world.pathSurface=road.AddComponent<MeshCollider>();world.pathSurface.sharedMesh=road.GetComponent<MeshFilter>().sharedMesh;
   // A continuous biscuit underside makes the trail a suspended three-dimensional landform.
   var bodyV=new List<Vector3>();var bodyUV=new List<Vector2>();var bodyT=new List<int>();
   for(int i=0;i<world.route.Length;i++){var a=left[i];var b=right[i];bodyV.AddRange(new[]{a,b,a+Vector3.down*1.6f,b+Vector3.down*1.6f});for(int k=0;k<4;k++)bodyUV.Add(new Vector2(k%2,i*.07f));if(i>0){int n=i*4,q=n-4;bodyT.AddRange(new[]{q,q+2,n,q+2,n+2,n,q+1,n+1,q+3,q+3,n+1,n+3,q+2,q+3,n+2,n+2,q+3,n+3});}}
   Part("Continuous suspended biscuit trail",parent,Save("Trail biscuit underside",CandyMeshKit.Build(bodyV,bodyT,bodyUV)),cake,Vector3.zero);
   Part("Left piped frosting",parent,Save("Trail left icing",Tube(left.ToArray(),.16f,10)),cream,Vector3.zero);Part("Right piped frosting",parent,Save("Trail right icing",Tube(right.ToArray(),.16f,10)),cream,Vector3.zero);
   // Physical and controller-compatible fences protect the full floating route.
   for(int i=0;i<world.route.Length-1;i+=4){int end=Mathf.Min(i+4,world.route.Length-1);foreach(int sign in new[]{-1,1}){var a=sign<0?left[i]:right[i];var b=sign<0?left[end]:right[end];Fence(parent,a,b,wood);}}
   for(int i=2;i<world.route.Length-2;i+=2){var p=world.route[i];var d=(world.route[i+1]-world.route[i-1]).normalized;var side=Vector3.Cross(Vector3.up,d);for(int j=0;j<3;j++){var sprinkle=Primitive("Trail confetti sprinkle",parent,PrimitiveType.Capsule,p+side*Random(-4.1f,4.1f)+Vector3.up*.105f,new Vector3(.045f,.13f,.045f),new[]{pink,gold,mint,lilac}[rng.Next(4)]);sprinkle.transform.rotation=Quaternion.Euler(90,Random(0,180),0);}}
  }
  static void Fence(Transform parent,Vector3 a,Vector3 b,Material mat){var direction=b-a;var center=(a+b)*.5f;var rail=Primitive("Candy edge safety rail",parent,PrimitiveType.Cube,center+Vector3.up*.85f,new Vector3(.15f,.18f,direction.magnitude+.12f),mat);rail.transform.rotation=Quaternion.LookRotation(direction);var box=rail.AddComponent<BoxCollider>();box.center=new Vector3(0,-.2f,0);box.size=new Vector3(2,7,1);solids.Add(box);var post=Primitive("Gold-tipped biscuit post",parent,PrimitiveType.Cylinder,a+Vector3.up*.55f,new Vector3(.22f,.55f,.22f),mat);Primitive("Sugar gold post cap",parent,PrimitiveType.Sphere,a+Vector3.up*1.13f,Vector3.one*.28f,gold);}
  static void BuildIslands(Transform env,CandyWorld world){var parent=Group("Floating cake islands",env);var profile=new[]{new Vector2(0,-7),new Vector2(.15f,-6),new Vector2(.45f,-4.8f),new Vector2(.75f,-2.8f),new Vector2(.98f,-.8f),new Vector2(1,0),new Vector2(.8f,.01f),new Vector2(0,.025f)};var mesh=Save("Organic floating cake island",Lathe(profile,64,.09f));
   foreach(int index in new[]{0,28,60,90,124,155,195,224,240}){var p=world.route[Mathf.Min(index,world.route.Length-1)];Island(parent,mesh,p,index==240||index==0?10:7,index==0?7:Random(4,6),index);}
   var islandCandyPrefabs=CandyVariants.Create();for(int i=0;i<18;i++){float a=i*2.399f;var p=new Vector3(Mathf.Cos(a)*Random(43,95),Random(-7,23),Mathf.Sin(a)*Random(40,95));Island(parent,mesh,p,Random(5,11),Random(4,8),i+300);if(i%3==0)MiniCastle(parent,p+Vector3.up*.15f,.26f);var prefabs=islandCandyPrefabs;for(int k=0;k<4;k++){float phi=k*2.399f;var candy=(GameObject)PrefabUtility.InstantiatePrefab(prefabs[(i+k*3)%9],parent);candy.transform.position=p+new Vector3(Mathf.Cos(phi)*3,.03f,Mathf.Sin(phi)*2.3f);candy.transform.localScale=Vector3.one*.45f;foreach(var box in candy.GetComponentsInChildren<BoxCollider>())box.enabled=false;}if(i%3==1)Waterfall(parent,p+new Vector3(2,0,-4),2.4f,18,ShaderMaterial("Pastel turquoise water","StudentWork/CandyWonderland/Silken Waterfall"),i+10);}
  }
  static void Island(Transform parent,Mesh mesh,Vector3 p,float rx,float rz,int seed){var body=Part("Floating biscuit island "+seed,parent,mesh,cake,p);body.transform.localScale=new Vector3(rx,1,rz);var frosting=Primitive("Rounded pink icing island cap",parent,PrimitiveType.Sphere,p-Vector3.up*.2f,new Vector3(rx*2,.38f,rz*2),seed%2==0?peach:cream);for(int i=0;i<12;i++){float a=i*Mathf.PI/6;Primitive("Frosting drip",parent,PrimitiveType.Sphere,p+new Vector3(Mathf.Cos(a)*rx*.94f,-.35f,Mathf.Sin(a)*rz*.94f),new Vector3(.6f,Random(.65f,1.5f),.6f),peach);}}
  static void BuildVegetation(Transform parent,CandyWorld world,StudentObstacleMovement movement){world.candyPrefabs=CandyVariants.Create();for(int i=0;i<58;i++){int index=3+i*4;index=Mathf.Min(index,world.route.Length-3);var p=world.route[index];var d=(world.route[index+1]-world.route[index-1]).normalized;var side=Vector3.Cross(Vector3.up,d);int sign=i%2==0?-1:1;float offset=Random(8.3f,10.5f);p+=side*offset*sign;var candy=(GameObject)PrefabUtility.InstantiatePrefab(world.candyPrefabs[i%9],parent);candy.name=CandyVariants.Names[i%9]+" "+i;candy.transform.position=p;candy.transform.rotation=Quaternion.Euler(0,Random(-35,35),Random(-7,7));float s=Random(.68f,1.35f);candy.transform.localScale=Vector3.one*s;var retained=movement.obstacles;movement.obstacles=candy.GetComponentsInChildren<BoxCollider>();foreach(float trial in new[]{offset*sign,-offset*sign,(offset+3)*sign,-(offset+3)*sign,(offset+9)*sign,-(offset+9)*sign,(offset+24)*sign,-(offset+24)*sign}){p=world.route[index]+side*trial;candy.transform.position=p;if(RouteClear(world,movement,candy.transform.position))break;}if(!RouteClear(world,movement,candy.transform.position))throw new Exception("Candy placement obstructs route: "+candy.name);movement.obstacles=retained;solids.AddRange(candy.GetComponentsInChildren<BoxCollider>());var pad=Part("Candy-root biscuit ledge",parent,AssetDatabase.LoadAssetAtPath<Mesh>(Art+"/Organic floating cake island.asset"),cake,p);pad.transform.localScale=new Vector3(2.7f,.3f,2.7f);Primitive("Candy-root frosting",parent,PrimitiveType.Sphere,p+Vector3.down*.18f,new Vector3(5.5f,.4f,5.5f),cream);for(int j=0;j<2;j++){var bush=Primitive("Gumdrop garden",parent,PrimitiveType.Sphere,p+new Vector3(Random(-1.7f,1.7f),.28f,Random(-1.2f,1.2f)),new Vector3(.8f,.7f,.8f),new[]{pink,mint,lilac,peach}[rng.Next(4)]);}}
   for(int i=0;i<18;i++){float a=i*2.399f;var p=new Vector3(Mathf.Cos(a)*Random(32,50),Random(-1,9),Mathf.Sin(a)*Random(32,50));var candy=(GameObject)PrefabUtility.InstantiatePrefab(world.candyPrefabs[(i*7)%9],parent);candy.transform.position=p;candy.transform.localScale=Vector3.one*Random(.4f,.7f);var ledge=Part("Distant candy islet",parent,AssetDatabase.LoadAssetAtPath<Mesh>(Art+"/Organic floating cake island.asset"),cake,p);ledge.transform.localScale=new Vector3(2.5f,.4f,2.5f);foreach(var renderer in candy.GetComponentsInChildren<MeshRenderer>())renderer.shadowCastingMode=ShadowCastingMode.Off;}
  }
  static bool RouteClear(CandyWorld world,StudentObstacleMovement movement,Vector3 garden){for(int i=0;i<world.route.Length-1;i++){if(Vector2.Distance(new Vector2(garden.x,garden.z),new Vector2(world.route[i].x,world.route[i].z))<7.7f)return false;var d=world.route[i+1]-world.route[i];d.y=0;if(movement.Penetration(world.route[i]+Vector3.up*.095f,Quaternion.LookRotation(d))>.001f)return false;}return true;}
  static void BuildBridges(Transform env,CandyWorld world){var parent=Group("Candy arch bridges",env);foreach(var pair in new[]{new[]{100,116},new[]{172,191}}){var a=world.route[pair[0]];var b=world.route[pair[1]];var center=(a+b)*.5f;var direction=b-a;var side=Vector3.Cross(Vector3.up,direction.normalized);for(int sign=-1;sign<=1;sign+=2){var points=Curve(t=>Vector3.Lerp(a,b,t)+side*sign*4.95f+Vector3.up*(.8f+Mathf.Sin(t*Mathf.PI)*.2f),48);Part("Pink bridge balustrade",parent,Save("Bridge rail "+pair[0]+" "+sign,Tube(points,.13f,10)),pink,Vector3.zero);for(int i=0;i<9;i++){var p=points[i*5];Primitive("Bridge gold spindle",parent,PrimitiveType.Cylinder,p-Vector3.up*.42f,new Vector3(.12f,.42f,.12f),gold);}}var arch=Curve(t=>Vector3.Lerp(a,b,t)+Vector3.down*(.4f+Mathf.Sin(t*Mathf.PI)*2.1f),48);for(int sign=-1;sign<=1;sign+=2)Part("Biscuit bridge arch",parent,Save("Bridge arch "+pair[0]+" "+sign,Tube(arch.Select(p=>p+side*sign*4.2f).ToArray(),.48f,10)),cream,Vector3.zero);}}
  static void BuildWaterfalls(Transform env,CandyWorld world){var parent=Group("Silken waterfalls",env);var water=ShaderMaterial("Pastel turquoise water","StudentWork/CandyWonderland/Silken Waterfall");for(int i=0;i<6;i++){int index=new[]{30,90,127,157,195,233}[i];var p=world.route[index]+new Vector3(i%2==0?6:-6,.05f,0);Waterfall(parent,p,Random(2,4),Random(12,21),water,i);}}
  static void Waterfall(Transform parent,Vector3 p,float width,float height,Material mat,int index){var v=new List<Vector3>();var uv=new List<Vector2>();var t=new List<int>();for(int j=0;j<=20;j++)for(int k=0;k<9;k++){v.Add(new Vector3((k/8f-.5f)*width,-j/20f*height,Mathf.Sin(j*.2f)*.13f));uv.Add(new Vector2(k/8f,j/20f));if(j>0&&k<8){int n=j*9+k,a=n-9;t.AddRange(new[]{a,a+1,n,n,a+1,n+1});}}Part("Animated waterfall "+index,parent,Save("Waterfall curtain "+index,CandyMeshKit.Build(v,t,uv)),mat,p);var mist=Primitive("Waterfall mist cloud",parent,PrimitiveType.Sphere,p+Vector3.down*(height*.72f),new Vector3(width*1.8f,1.5f,2),cloud);}
  static Transform BuildCastle(Transform env,Vector3 p){var parent=Group("Candy castle - finish landmark",env);parent.position=p+new Vector3(-2,0,0);parent.rotation=Quaternion.Euler(0,-90,0);MiniCastle(parent,Vector3.zero,1);return parent;}
  static void MiniCastle(Transform parent,Vector3 p,float scale){var castle=Group("Sugar palace",parent);castle.localPosition=p;castle.localScale=Vector3.one*scale;
   // Leave the central gateway genuinely open for the elephant and finale.
   foreach(int sign in new[]{-1,1}){Primitive("Cream gate wing",castle,PrimitiveType.Cube,new Vector3(sign*7,4,1),new Vector3(5,8,2.1f),cream).AddComponent<BoxCollider>();for(int row=0;row<3;row++)for(int col=0;col<3;col++)Primitive("Golden glowing window",castle,PrimitiveType.Capsule,new Vector3(sign*(5.2f+col*1.5f),2+row*2.15f,-.1f),new Vector3(.47f,.7f,.1f),gold);}
   Primitive("Gate arch keystone",castle,PrimitiveType.Cube,new Vector3(0,8.3f,1),new Vector3(9.5f,1.8f,2.1f),peach);
   foreach(var data in new[]{new Vector3(-10,0,3),new Vector3(10,0,3),new Vector3(-6,0,6),new Vector3(6,0,6),new Vector3(0,0,9),new Vector3(-13,0,8),new Vector3(13,0,8)}){float h=10+(data.x==0?6:Mathf.Abs(data.x)<9?2:0);Primitive("Rose sugar tower",castle,PrimitiveType.Cylinder,data+Vector3.up*h*.5f,new Vector3(2.9f,h*.5f,2.9f),Mathf.Abs(data.x)<9?peach:pink).AddComponent<BoxCollider>();var roof=Save("Castle conical roof "+h,Lathe(new[]{new Vector2(1.85f,0),new Vector2(1.9f,.25f),new Vector2(.09f,4.3f),new Vector2(0,4.6f)},48));Part("Elegant pink turret roof",castle,roof,pink,data+Vector3.up*h);Primitive("Golden turret finial",castle,PrimitiveType.Sphere,data+Vector3.up*(h+4.65f),Vector3.one*.43f,gold);for(int k=0;k<3;k++)Primitive("Tower luminous window",castle,PrimitiveType.Capsule,data+new Vector3(0,2.5f+k*2.5f,-1.45f),new Vector3(.6f,.85f,.08f),gold);}
   for(int i=0;i<11;i++)Primitive("Sugar battlement",castle,PrimitiveType.Cube,new Vector3(-9+i*1.8f,9.4f,1),new Vector3(.7f,.7f,2.2f),cream);
   var gateway=Primitive("Gateway warm glow",castle,PrimitiveType.Sphere,new Vector3(0,4,2.5f),new Vector3(7,7,.1f),Mat("Gateway glow",new Color(1,.73f,.72f,.22f),.8f,true));
  }
  static void BuildBalls(Transform parent,CandyWorld world,StudentObstacleMovement movement,DigiPhantLocomotion loco,RibbonFinish finish){for(int i=0;i<3;i++){int index=new[]{73,138,183}[i];var center=world.route[index];var along=(world.route[index+1]-world.route[index-1]).normalized;var across=Vector3.Cross(Vector3.up,along).normalized;if(i==1)across=new Vector3(along.x,0,along.z).normalized;float radius=1.12f+i*.1f;var host=new GameObject("Rolling candy "+(i+1));host.transform.SetParent(parent,false);var ball=host.AddComponent<RollingCandyBall>();ball.radius=radius;ball.speed=1.2f+i*.15f;ball.endpointPause=1.8f+i*.4f;ball.start=center-across*2.4f+Vector3.up*(radius+.06f);ball.end=center+across*2.4f+Vector3.up*(radius+.06f);ball.start=new Vector3(ball.start.x,world.GroundHeight(ball.start)+radius+.06f,ball.start.z);ball.end=new Vector3(ball.end.x,world.GroundHeight(ball.end)+radius+.06f,ball.end.z);ball.initialProgress=i==0?.12f:i==1?.7f:.4f;ball.movement=movement;ball.elephant=loco.travelRoot;ball.finish=finish;var visual=Primitive("Glossy striped candy ball",host.transform,PrimitiveType.Sphere,Vector3.zero,Vector3.one*radius*2,CandyVariants.StripeMaterial("Hazard "+i,new[]{new Color(1,.37f,.62f),new Color(.6f,.88f,.73f),new Color(1,.7f,.47f)}[i]));ball.visual=visual.transform;ball.solid=host.AddComponent<BoxCollider>();ball.solid.size=Vector3.one*radius*2;solids.Add(ball.solid);ball.Initialize();}}
  static void BuildAtmosphere(Transform parent,CandyWorld world){var clouds=new List<Transform>();var balloons=new List<Transform>();for(int i=0;i<80;i++){float angle=i*2.399f;float radius=i<25?Random(10,38):Random(45,125);var p=new Vector3(Mathf.Cos(angle)*radius,i<25?Random(-13,-8):Random(-15,22),Mathf.Sin(angle)*radius);var group=Group("Drifting marshmallow cloud "+i,parent);group.position=p;float size=Random(5,13);for(int j=0;j<6;j++)Primitive("Soft cloud billow",group,PrimitiveType.Sphere,new Vector3(Random(-.6f,.6f)*size,Random(-.1f,.25f)*size,Random(-.4f,.4f)*size),new Vector3(size,size*.7f,size*.83f),i%3==0?LavenderCloud():cloud);CombineVisuals(group,"Cloud cluster "+i,false);clouds.Add(group);}
   for(int i=0;i<9;i++){float a=i*2.399f;var balloon=Group("Pastel sky balloon "+i,parent);balloon.position=new Vector3(Mathf.Cos(a)*Random(32,75),Random(12,26),Mathf.Sin(a)*Random(32,75));var globe=Primitive("Striped balloon envelope",balloon,PrimitiveType.Sphere,Vector3.zero,new Vector3(3.5f,4.8f,3.5f),CandyVariants.StripeMaterial("Balloon silk "+i,new[]{new Color(1,.58f,.76f),new Color(.74f,.64f,.92f),new Color(.6f,.85f,.73f)}[i%3]));Primitive("Wicker gondola",balloon,PrimitiveType.Cylinder,new Vector3(0,-3.5f,0),new Vector3(1.1f,.4f,1.1f),wood);foreach(int sign in new[]{-1,1})Primitive("Balloon golden rigging",balloon,PrimitiveType.Cylinder,new Vector3(sign*.44f,-2.65f,0),new Vector3(.035f,.6f,.035f),gold);balloons.Add(balloon);}
   var effect=parent.gameObject.AddComponent<CandyAtmosphere>();effect.clouds=clouds.ToArray();effect.balloons=balloons.ToArray();
   // Low-cost decorative sparkle field above and outside the walkable route.
   var sparkles=new GameObject("Magical sky sparkles");sparkles.transform.SetParent(parent,false);sparkles.transform.position=Vector3.up*6;var ps=sparkles.AddComponent<ParticleSystem>();var main=ps.main;main.startLifetime=6;main.startSpeed=.04f;main.startSize=.09f;main.startColor=new Color(1,.91f,.62f,.55f);main.maxParticles=120;var emission=ps.emission;emission.rateOverTime=14;var shape=ps.shape;shape.shapeType=ParticleSystemShapeType.Box;shape.scale=new Vector3(58,14,58);var renderer=ps.GetComponent<ParticleSystemRenderer>();var material=Mat("Soft golden sparkles",new Color(1,.85f,.5f,.6f),.7f,true);renderer.sharedMaterial=material;
  }
  static void StyleTitle(LevelIntroduction intro){
   var panel=intro.group.GetComponent<RectTransform>();panel.anchorMin=new Vector2(.12f,.38f);panel.anchorMax=new Vector2(.88f,.62f);var background=panel.GetComponent<Image>();background.enabled=false;var plaqueObject=new GameObject("Frosting cloud title backdrop",typeof(RectTransform),typeof(CanvasRenderer),typeof(CandyCloudPlaque));plaqueObject.transform.SetParent(panel,false);plaqueObject.transform.SetAsFirstSibling();var plaqueRect=plaqueObject.GetComponent<RectTransform>();plaqueRect.anchorMin=Vector2.zero;plaqueRect.anchorMax=Vector2.one;plaqueRect.offsetMin=plaqueRect.offsetMax=Vector2.zero;var plaque=plaqueObject.GetComponent<CandyCloudPlaque>();plaque.color=new Color(1,.96f,.9f,.86f);plaque.raycastTarget=false;plaque.textArea=intro.title.rectTransform;
   intro.title.supportRichText=true;intro.title.text="<size=36>Level 1:</size>\nLollipop Forest";intro.title.color=new Color(.91f,.28f,.51f);intro.title.fontStyle=FontStyle.Bold;intro.title.resizeTextMaxSize=66;intro.title.resizeTextMinSize=18;var shadow=intro.title.GetComponent<Shadow>();shadow.effectColor=new Color(.42f,.18f,.35f,.65f);shadow.effectDistance=new Vector2(3,-4);var outline=intro.title.gameObject.AddComponent<Outline>();outline.effectColor=new Color(1,.99f,.87f,.9f);outline.effectDistance=new Vector2(1.5f,1.5f);
   var floatMotion=intro.gameObject.AddComponent<CandyTitleFloat>();floatMotion.panel=panel;
   for(int i=0;i<4;i++){var go=new GameObject("Title sugar star",typeof(RectTransform),typeof(Text));go.transform.SetParent(panel,false);var rect=go.GetComponent<RectTransform>();rect.anchorMin=rect.anchorMax=new Vector2(i%2==0?.06f:.94f,i<2?.2f:.8f);rect.sizeDelta=new Vector2(48,48);var text=go.GetComponent<Text>();text.font=intro.title.font;text.text="✦";text.fontSize=38;text.alignment=TextAnchor.MiddleCenter;text.color=i%2==0?new Color(1,.73f,.28f):new Color(1,.49f,.7f);text.raycastTarget=false;}
   intro.SetElapsed(intro.Duration);
  }
  static void ConfigureLighting(Transform env,Camera camera){var sky=ShaderMaterial("Candy sunrise sky","StudentWork/CandyWonderland/Pastel Sky");sky.SetColor("_Top",new Color(.61f,.8f,1));sky.SetColor("_Horizon",new Color(1,.85f,.81f));sky.SetColor("_Bottom",new Color(.84f,.81f,.96f));RenderSettings.skybox=sky;DynamicGI.UpdateEnvironment();RenderSettings.ambientMode=AmbientMode.Trilight;RenderSettings.ambientSkyColor=new Color(.8f,.85f,1);RenderSettings.ambientEquatorColor=new Color(1,.79f,.83f);RenderSettings.ambientGroundColor=new Color(.72f,.64f,.79f);RenderSettings.ambientIntensity=.85f;RenderSettings.fog=true;RenderSettings.fogMode=FogMode.ExponentialSquared;RenderSettings.fogDensity=.006f;RenderSettings.fogColor=new Color(.91f,.8f,.89f);foreach(var light in UnityEngine.Object.FindObjectsByType<Light>(FindObjectsSortMode.None))if(light.type==LightType.Directional){light.color=new Color(1,.94f,.87f);light.shadowStrength=.4f;light.intensity=1.1f;light.shadows=LightShadows.Soft;light.transform.rotation=Quaternion.Euler(37,-28,0);}
   if(camera){camera.clearFlags=CameraClearFlags.Skybox;var data=camera.GetUniversalAdditionalCameraData();data.renderPostProcessing=true;}
   var volumeObject=new GameObject("Candy sunrise bloom");volumeObject.transform.SetParent(env,false);var volume=volumeObject.AddComponent<Volume>();volume.isGlobal=true;volume.priority=10;var profile=AssetDatabase.LoadAssetAtPath<VolumeProfile>(Art+"/Candy sunrise atmosphere.asset");bool newProfile=!profile;if(newProfile)profile=ScriptableObject.CreateInstance<VolumeProfile>();profile.name="Candy sunrise atmosphere";if(!profile.TryGet<Bloom>(out var bloom))bloom=profile.Add<Bloom>(true);bloom.intensity.Override(.16f);bloom.threshold.Override(1.2f);if(!profile.TryGet<Tonemapping>(out var tone))tone=profile.Add<Tonemapping>(true);tone.mode.Override(TonemappingMode.ACES);if(newProfile)AssetDatabase.CreateAsset(profile,Art+"/Candy sunrise atmosphere.asset");volume.sharedProfile=profile;
  }
 }
}
