using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEditor;
namespace StudentWork.CandyWonderland.Editor {
 public static class CandyMeshKit {
  public const string Art="Assets/StudentWork/CandyWonderland/Art";
  public static Mesh Save(string name,Mesh mesh){string path=Art+"/"+name+".asset";var old=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(old){mesh.name=name;EditorUtility.CopySerialized(mesh,old);EditorUtility.SetDirty(old);UnityEngine.Object.DestroyImmediate(mesh);return old;}mesh.name=name;mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,path);return mesh;}
  public static Material Mat(string name,Color color,float smooth=.7f,bool transparent=false){string path=Art+"/"+name+".mat";var old=AssetDatabase.LoadAssetAtPath<Material>(path);if(old)return old;var m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=name};m.SetColor("_BaseColor",color);m.SetFloat("_Smoothness",smooth);m.SetFloat("_Metallic",.06f);if(transparent){m.SetFloat("_Surface",1);m.SetFloat("_SrcBlend",5);m.SetFloat("_DstBlend",10);m.SetFloat("_ZWrite",0);m.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");m.renderQueue=3000;}AssetDatabase.CreateAsset(m,path);return m;}
  public static GameObject Part(string name,Transform parent,Mesh mesh,Material mat,Vector3 pos){var g=new GameObject(name);g.transform.SetParent(parent,false);g.transform.localPosition=pos;g.AddComponent<MeshFilter>().sharedMesh=mesh;g.AddComponent<MeshRenderer>().sharedMaterial=mat;return g;}
  public static GameObject Primitive(string name,Transform parent,PrimitiveType type,Vector3 pos,Vector3 scale,Material mat){var g=GameObject.CreatePrimitive(type);g.name=name;g.transform.SetParent(parent,false);g.transform.localPosition=pos;g.transform.localScale=scale;UnityEngine.Object.DestroyImmediate(g.GetComponent<Collider>());g.GetComponent<MeshRenderer>().sharedMaterial=mat;return g;}
  public static Mesh Tube(Vector3[] points,float radius,int sides=8){var v=new List<Vector3>();var tri=new List<int>();var uv=new List<Vector2>();for(int i=0;i<points.Length;i++){var tangent=(points[Mathf.Min(i+1,points.Length-1)]-points[Mathf.Max(0,i-1)]).normalized;var u=Vector3.Cross(tangent,Mathf.Abs(tangent.y)>.95f?Vector3.right:Vector3.up).normalized;var w=Vector3.Cross(tangent,u).normalized;for(int j=0;j<sides;j++){float a=j*Mathf.PI*2/sides;v.Add(points[i]+radius*(u*Mathf.Cos(a)+w*Mathf.Sin(a)));uv.Add(new Vector2(j/(float)sides,i/(float)(points.Length-1)));if(i>0){int n=i*sides+j,p=(i-1)*sides+j,q=(j+1)%sides;tri.AddRange(new[]{p,(i-1)*sides+q,n,n,(i-1)*sides+q,i*sides+q});}}}return Build(v,tri,uv);}
  public static Mesh Shape(Func<float,Vector2> outline,float depth){const int count=96;var v=new List<Vector3>();var tri=new List<int>();var uv=new List<Vector2>();for(int face=0;face<2;face++){v.Add(new Vector3(0,0,face==0?-depth:depth));uv.Add(new Vector2(.5f,.5f));for(int i=0;i<count;i++){var p=outline(i*Mathf.PI*2/count);v.Add(new Vector3(p.x,p.y,face==0?-depth:depth));uv.Add(p*.5f+Vector2.one*.5f);}for(int i=0;i<count;i++){int a=face*(count+1),b=a+1+i,c=a+1+(i+1)%count;tri.AddRange(face==0?new[]{a,c,b}:new[]{a,b,c});}}for(int i=0;i<count;i++){int a=1+i,b=1+(i+1)%count,c=a+count+1,d=b+count+1;tri.AddRange(new[]{a,b,c,c,b,d});}return Build(v,tri,uv);}
  public static Mesh Lathe(Vector2[] profile,int sides=48,float irregular=0){var v=new List<Vector3>();var t=new List<int>();var uv=new List<Vector2>();for(int r=0;r<profile.Length;r++)for(int s=0;s<=sides;s++){float a=s*Mathf.PI*2/sides;float radius=profile[r].x*(1+irregular*(Mathf.Sin(a*3+.2f)+.4f*Mathf.Sin(a*7)));v.Add(new Vector3(Mathf.Cos(a)*radius,profile[r].y,Mathf.Sin(a)*radius));uv.Add(new Vector2(s/(float)sides,r/(float)(profile.Length-1)));if(r>0&&s<sides){int n=r*(sides+1)+s,p=n-sides-1;t.AddRange(new[]{p,n,p+1,p+1,n,n+1});}}return Build(v,t,uv);}
  public static Mesh Build(List<Vector3> v,List<int> t,List<Vector2> uv){var m=new Mesh();if(v.Count>65000)m.indexFormat=UnityEngine.Rendering.IndexFormat.UInt32;m.SetVertices(v);m.SetTriangles(t,0);m.SetUVs(0,uv);m.RecalculateNormals();m.RecalculateBounds();return m;}
  public static void CombineVisuals(Transform root,string name,bool shadows=true){
   var renderers=root.GetComponentsInChildren<MeshRenderer>().Where(r=>r.enabled&&r.sharedMaterials.Length==1).ToArray();int index=0;
   foreach(var group in renderers.GroupBy(r=>r.sharedMaterial)){var instances=group.Select(r=>new CombineInstance{mesh=r.GetComponent<MeshFilter>().sharedMesh,transform=root.worldToLocalMatrix*r.transform.localToWorldMatrix}).ToArray();var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.CombineMeshes(instances,true,true);var part=Part("Batched candy decoration",root,Save(name+" batch "+index++,mesh),group.Key,Vector3.zero);part.GetComponent<MeshRenderer>().shadowCastingMode=shadows?UnityEngine.Rendering.ShadowCastingMode.On:UnityEngine.Rendering.ShadowCastingMode.Off;foreach(var r in group)r.enabled=false;}
  }
  public static Vector3[] Curve(Func<float,Vector3> sample,int count=120){var p=new Vector3[count];for(int i=0;i<count;i++)p[i]=sample(i/(float)(count-1));return p;}
 }
}
